Repository GSG-G13/basel-mohannd-db, pull requests merged in 2023-04, with the labels that each got.

#2 create project structure
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  public/js/main.js
  public/profile.html
  src/app.js
  src/controllers/handlers.js
  src/controllers/index.js
  src/index.js
Labels: merged

#4 add html files
  .gitignore
  public/index.html
  public/profile.html
Labels: waiting

#8 7-setting-up-server
  src/app.js
  src/index.js
Labels: merged

#10 setting up server
  src/database/config/build.sql
Labels: merged

#12 create connection file
  src/app.js
  src/database/config/connection.js
Labels: waiting

#16 15 render profile page with user data
  public/css/style.css
  public/js/fetchUserData.js
  public/js/main.js
  public/profile.html
  public/userNotFound.html
  src/app.js
  src/controllers/handlers.js
  src/controllers/index.js
  src/database/config/build.sql
  src/database/queries/getUser.js
Labels: in progress
